encoding: utf-8
collections:
  experience:
    output: true
    sort_by: order
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
# Setup
title: Ritik Kumar
tagline: ''
description: |
  <div class="image">
    <img class="thumbnail" src="/public/assets/me.jpg">
  </div>
url: https://ritik.ml
baseurl: ''
paginate: 4
permalink: pretty
paginate_path: "/page/:num/"

# About/contact
author:
  name: Ritik Kumar
  url: https://twitter.com/ritik___

# Gems
plugins:
  - jekyll-paginate

# Sass settings
sass:
  sass_dir: _scss
  style: :compressed

# Custom vars
version: 0.1.0
head: "/public/assets/me.jpg"

exclude:
  - medium-to-markdown*
  - package*
  - node_modules/
  - README.md
