encoding: UTF-8
collections:
  experience:
    output: true
    sort_by: order
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
# Setup
title: Ritik Kumar
tagline: ''

url: https://ritik.ga
base_domain: ritik.ga # For hosted subdomains
baseurl: ''
paginate: 4
permalink: pretty
paginate_path: "/page/:num/"

# About/contact
author:
  name: Ritik Kumar
  twitter_username: ritik___
  github_username: dev-ritik
  linkedin_username: ritik-kumar
  medium_url: https://ritikk.medium.com
  email: ritikkne@gmail.com
  youtube_handle: kumar_ritik

# Gems
plugins:
  - jekyll-paginate

# Sass settings
sass:
  sass_dir: _scss
  style: compressed

# Custom vars
version: 0.1.0
head: "/public/assets/me/me_364.jpg"

exclude:
  - medium-to-markdown*
  - package*
  - node_modules/
  - README.md
